<?php

/**
* Trait TestCar1952538869Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;


use App\Models\TestCar2560124850;

trait TestCar1952538869Trait
{
    
    public function getTable()
    {
        return $this->table ?? 'test_cars';
    }

    public function getFillable()
    {
        return $this->fillable ?? [
                            'test',
                    ];
    }

                                        public function has_many_relation(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(App\Models\TestCar2560124850::class, 'testCar1952538869_id', 'id');
            }
            }
