<?php
/**
* Trait TestCar2330027336Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar2330027336Trait
{
    
    public function getTable()
    {
        return $this->table ?? 'test_cars_2';
    }

    public function getFillable()
    {
        if (!empty($this->fillable)) {
            return $this->fillable;
        }

        return [
                    ];
    }

    }
