<?php

/**
* Trait TestCar2631586454Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar2631586454Trait
{
    
    protected $table = 'test_cars_2';

    protected $fillable = [
            ];
    }
