<?php

/**
* Trait TestCar1015982843Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar1015982843Trait
{
    
    protected $table = 'test_cars';

    protected $fillable = [
                    'test',
            ];
                                        public function has_many_relation(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(App\Models\TestCar2354222993::class, 'testCar1015982843_id', 'id');
            }
            }
