<?php

/**
* Trait TestCar1018352743Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;


use App\Models\TestCar2785729629;

trait TestCar1018352743Trait
{
    
    public function getTable()
    {
        return $this->table ?? 'test_cars';
    }

    public function getFillable()
    {
        return $this->fillable ?? [
                            'test',
                    ];
    }

                                        public function has_many_relation(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(App\Models\TestCar2785729629::class, 'testCar1018352743_id', 'id');
            }
            }
