<?php

/**
* Trait TestCar1076792425Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar1076792425Trait
{
    
    protected $table = 'test_cars';

    protected $fillable = [
                    'test',
            ];
                                        public function has_many_relation(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(App\Models\TestCar2396308069::class, 'testCar1076792425_id', 'id');
            }
        ;
    }
