<?php

/**
* Trait TestCar270677603Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar270677603Trait
{
    
    protected $table = 'test_cars_2';

    protected $fillable = [
            ];
    }
