<?php

/**
* Trait TestCar2013868899Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar2013868899Trait
{
    
    protected $table = 'test_cars';

    protected $fillable = [
                    'test',
            ];
                                        public function has_many_relation(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(App\Models\TestCar2655759571::class, 'testCar2013868899_id', 'id');
            }
        ;
    }
