<?php

/**
* Trait TestCar14268556Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;
    use App\Model\TestCar2935725681;

trait TestCar14268556Trait
{
    
    public function getTable()
    {
        return $this->table ?? 'test_cars';
    }

    public function getFillable()
    {
        return $this->fillable ?? [
                            'test',
                    ];
    }

                                        public function has_many_relation(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(App\Models\TestCar2935725681::class, 'testCar14268556_id', 'id');
            }
            }
