<?php

/**
* Trait TestCar807149302Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar807149302Trait
{
    
    protected $table = 'test_cars';

    protected $fillable = [
                    'test',
            ];
                                        public function has_many_relation(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(App\Models\TestCar21177451419::class, 'testCar807149302_id', 'id');
            }
        ;
    }
