<?php
/**
* Trait TestCar551476458Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar551476458Trait
{
    
    public function getCasts()
    {
        $casts = parent::getCasts();
                            
        return $casts;
    }

    public function getTable()
    {
        return $this->table ?? 'test_cars';
    }

    public function getFillable()
    {
        if (!empty($this->fillable)) {
            return $this->fillable;
        }

        return [
                            'test',
                    ];
    }

                                        public function hasManyRelation(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(\App\Models\TestCar21666236528::class, 'ricardo_haley_id', 'id');
            }
            }
