<?php
/**
* Trait TestCar21080636978Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar21080636978Trait
{
    
    public function getTable()
    {
        return $this->table ?? 'test_cars_2';
    }

    public function getFillable()
    {
        return $this->fillable ?? [
                    ];
    }

    }
