<?php
/**
* Trait TestCar762059127Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;


use App\Models\TestCar21546822451;

trait TestCar762059127Trait
{
    
    public function getTable()
    {
        return $this->table ?? 'test_cars';
    }

    public function getFillable()
    {
        return $this->fillable ?? [
                            'test',
                    ];
    }

                                        public function has_many_relation(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(App\Models\TestCar21546822451::class, 'testCar762059127_id', 'id');
            }
            }
