<?php

/**
* Trait TestCar21775823819Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar21775823819Trait
{
    
    protected $table = 'test_cars_2';

    protected $fillable = [
            ];
    }
