<?php
/**
* Trait TestCar2395769752Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar2395769752Trait
{
    
    public function getTable()
    {
        return $this->table ?? 'test_cars_2';
    }

    public function getFillable()
    {
        return $this->fillable ?? [
                    ];
    }

    }
