<?php

/**
* Trait TestCar22090234732Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar22090234732Trait
{
    
    protected $table = 'test_cars_2';

    protected $fillable = [
            ];
    }
