<?php

/**
* Trait TestCar213895648Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar213895648Trait
{
    
    protected $table = 'test_cars_2';

    protected $fillable = [
            ];
    }
