<?php

/**
* Trait TestCar1777383326Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar1777383326Trait
{
    
    protected $table = 'test_cars';

    protected $fillable = [
                    'test',
            ];
                                        public function has_many_relation(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(App\Models\TestCar21158215683::class, 'testCar1777383326_id', 'id');
            }
        ;
    }
