<?php
/**
* Trait TestCar2423767110Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar2423767110Trait
{
    
    public function getCasts()
    {
        $casts = parent::getCasts();
        
        return $casts;
    }

    public function getTable()
    {
        return $this->table ?? 'test_cars_2';
    }

    public function getFillable()
    {
        if (!empty($this->fillable)) {
            return $this->fillable;
        }

        return [
                    ];
    }

    }
