<?php

/**
* Trait TestCar2929148638Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;



trait TestCar2929148638Trait
{
    
    protected $table = 'test_cars_2';

    protected $fillable = [
            ];
    }
