<?php

/**
* Trait TestCar2061013842Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;


use App\Models\TestCar2696937327;

trait TestCar2061013842Trait
{
    
    public function getTable()
    {
        return $this->table ?? 'test_cars';
    }

    public function getFillable()
    {
        return $this->fillable ?? [
                            'test',
                    ];
    }

                                        public function has_many_relation(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(App\Models\TestCar2696937327::class, 'testCar2061013842_id', 'id');
            }
            }
