<?php

/**
* Trait TestCar2928144845Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar2928144845Trait
{
    
    protected $table = 'test_cars_2';

    protected $fillable = [
            ];
    }
