<?php
/**
* Trait TestCar898972813Trait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait TestCar898972813Trait
{
    
    public function getTable()
    {
        return $this->table ?? 'test_cars';
    }

    public function getFillable()
    {
        if (!empty($this->fillable)) {
            return $this->fillable;
        }

        return [
                            'test',
                    ];
    }

                                        public function hasManyRelation(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(\App\Models\TestCar21637820003::class, 'antonetta_king_id', 'id');
            }
            }
