<?php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;

/**
 * Service Provider LaragenServiceProvider
 *
 * Generated by LaraGen, Do not modify it manually.
 */
class LaragenServiceProvider extends ServiceProvider
{
    public function register()
    {

    }

    public function boot()
    {
        $this->loadRoutesFrom(__DIR__ . '/../../routes/laragen/web.php');
        $this->loadRoutesFrom(__DIR__ . '/../../routes/laragen/api.php');
    }
}
